# Example command configuration file - for quickly executing system commands
# Global default display mode (used when no category is specified)
display = "picture"

# Commands category - uses default "text" display mode since no display is specified
[commands]
display = "text"

[commands.entries]
"Shutdown" = "shutdown now"
"Reboot" = "reboot"
"Lock Screen" = "loginctl lock-session"
"Volume Up" = "pactl set-sink-volume @DEFAULT_SINK@ +5%"
"Volume Down" = "pactl set-sink-volume @DEFAULT_SINK@ -5%"
"Mute Toggle" = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
"Screenshot" = "gnome-screenshot"
"Record Screen" = "gnome-screenshot --record"
"xxx" = "I want to offer this for free for anyone to use. It's a simple go binary in a docker image (to make it easy to self-hosting and test locally) but it needs to live on the internet."
"yyy" = """
Even if the signaling server is manipulated, to hook up two peers which shouldn't be connected, the user won't be able to execute commands unless they can provide a valid OTP.
Better still the Signaling server (which I run) is never sent either the OTP or the OTP Secret used to validate each OTP.
This validation happens between two peers you own (Actions VM and your Browser).
"""

# Live wallpapers category - explicitly set to "picture" display mode
[live]
display = "picture"

[live.entries]
"wallpapers" = "~/Pictures/wallpapers/ja/"

[clip]
display = "picture"
source = "command"
[clip.entries]
"test_source" = """
echo -e "Option 1\nOption 2\nOption 3"
"""


[cliphist]
display = "picture"
source = "dynamic"
[cliphist.entries]
"cliphist list | awk '{print $1 \"\\t\" substr($0, index($0,$2))}' | head -n 5" = "cliphist decode {}"
